### ISSUE TITLE
isValid returns false

### ISSUE THREAD

**Issue by r3mi** [spatialillusions/milsymbol#204] opened 2018-09-28 06:12 UTC
In my tests, `Symbol.isValid` seems to always return `false`.
Example:
```js
var ms = require("milsymbol");

var symbol = new ms.Symbol("SFGPUCI----D");
console.log(symbol.isValid(true));
console.log(symbol.isValid());
```
Result:
```js
{ drawInstructions: false, icon: true, mobility: true }
false
```
I would expect `true` for such a valid SIDC.
Am I missing something ?

**Comment by spatialillusions** [comment] 2018-10-22 06:31
I'm not able to reproduce this at the moment, what version of milsymbol were you using?

**Comment by r3mi** [comment] 2018-10-22 18:48
Version 1.3.3 , through NPM
```js
var ms = require("milsymbol");

console.log(ms.getVersion());

var symbol = new ms.Symbol("SFGPUCI----D");
console.log(symbol.isValid(true));
console.log(symbol.isValid());
```
gives
```
milsymbol.js 1.3.3 - Copyright (c) 2017 Måns Beckman  http://www.spatialillusions.com
1.3.3
{ drawInstructions: false, icon: true, mobility: true }
false
```

**Comment by spatialillusions** [comment] 2018-10-25 15:56
Fixed in major branch.

**Closed by spatialillusions** 2018-10-25 15:56 UTC
