### ISSUE TITLE
Split library into multiple files/modules

### ISSUE THREAD

**Issue by kjellmf** [spatialillusions/milsymbol#9] opened 2014-10-30 16:48 UTC
The MilSymbol library is currently one big file. It is easier to maintain if you split it into multiple files. You can always use a build tool like Gulp or Grunt to combine and compress all the files for deployment.  This will probably also make it possible to create custom versions of MilSymbol. For example, if you don't need support for MILSTD 2525D, you don't need to include it in the project.

**Comment by spatialillusions** [comment] 2015-06-19 08:22
This will be possible after the release of milsymbol 0.5, where the code is much more modular.

**Comment by spatialillusions** [comment] 2016-09-09 11:07
I'm looking into different build tools to be able to split up milsymbol during development and assembly the parts in to a complete build. 
The simplest thing would be a make file concatenating the files to milsymbol.js, I have also looked into npm and other build tools. (Using npm would be very similar to a make file)

My idea is to use something that requires minimal external dependencies, and minimal changes to existing code. Milsymbol is already built so that it can be separated into several different files and assembled in different.

If there is anyone who has any other ideas all input is welcome.

**Comment by kjellmf** [comment] 2016-09-09 19:08
[Webpack](https://webpack.github.io/docs/) is quite popular. It will, however, probably require some modification to the source code. Most modern JS-libraries tend to split the code into smaller files/modules. Webpack then only include the code that is actually used.

**Comment by okwolf** [comment] 2016-09-10 16:41
I believe the simplest possible option would be to simply add to the [`"scripts"` in your package.json](https://docs.npmjs.com/misc/scripts) if your build process is merely calling other CLI tools like [`eslint`](http://eslint.org) (personally recommended), [`uglify`](https://github.com/mishoo/UglifyJS), etc.

The next level of complexity up from there is [webpack](https://webpack.github.io), which I consider best-in-breed for JS build tools today, although generally more useful for a full application where you want tools such as hot module reloading and the like.

There are even more advanced options like [Gulp](http://gulpjs.com) and [Grunt](http://gruntjs.com), although I can't think of any reasons you'd want to go that route.

No matter what build system you end up using I also recommend adding some amount of unit tests as part of the build. I have some tests that I currently use to regression test #40 and #44 that I would be happy to contribute back toward that cause. Finally, once the build is automated, I suggest looking into setting up a Continuous Integration (CI) build with something like [Travis CI](https://travis-ci.org). This can even be setup to automatically [publish to npm](https://docs.travis-ci.com/user/deployment/npm) by simply pushing a tag to the repo.

**Comment by spatialillusions** [comment] 2016-09-11 12:48
Thank you very much for your input, I had started looking into npm scripts, and have now had a look at webpack as well. I agree with you that Gulp or Grunt will be too much and I want to keep everything as simple as possible. For me there is no problem just having everything in one file, but I get more and more requests about special modifications and want to make it easier to modify one part of milsymbol but keep having updates for the rest. 

I'll get back to you when I have had a bit more time looking into this, but your unit tests sounds interesting.

**Comment by spatialillusions** [comment] 2016-11-11 16:14
@okwolf, any framework for tests that you recommend?

**Comment by okwolf** [comment] 2016-11-12 08:22
@spatialillusions: on my current projects I'm using [Mocha](https://mochajs.org) as it seems to be the most active and has good tooling/feedback for the dev tools I'm using. I've previously used [Jasmine](https://jasmine.github.io) which comes with more features out of the box, especially if you intend to write more complex acceptance tests in addition to unit tests.

On the simpler side, there are lighter weight options such as [tape](https://github.com/substack/tape) or using an assertion library like [Chai](http://chaijs.com) directly.

**Comment by spatialillusions** [comment] 2017-01-15 15:37
I have made some treats with this during the weekend and it looks like everything is working so I made a webpack branch with the code. 

There are still things that needs to be restructured, but all functionality should be in place. 

Since this is a quite big change it would be good if some people could beta test this and see if anything is broken. Especially if you use milsymbol in other webpack/browserfy/commonjs projects, since I did some changes to the module.exports code that was included in milsymbol 0.6.0.

**Comment by kjellmf** [comment] 2017-01-17 07:31
Unfortunately I can't get the new version to work with my setup. As a test I created a new project with the following setup:

`package.json`:
```
{
  "name": "wp-test",
  "version": "1.0.0",
  "dependencies": {
    "milsymbol": "github:spatialillusions/milsymbol#webpack"
  },
  "devDependencies": {
    "webpack": "^1.14.0"
  }
}
```

`webpack.config.json`:
```
module.exports = {
     entry: './src/app.js',
     output: {
         path: './bin',
         filename: 'app.bundle.js'
     }
 };
```

`src/app.js`:
```
var MS = require('milsymbol');

var symb= new MS.symbol("sfgpewrh--mt", {
    size: 35,
    quantity: 200,
    staffComments: "for reinforcements".toUpperCase(),
    additionalInformation: "added support for JJ".toUpperCase(),
    direction: (750*360/6400),
    type: "machine gun".toUpperCase(),
    dtg: "30140000ZSEP97",
    location: "0900000.0E570306.0N"
}).getMarker().XML;

document.write(symb);
```
`index.html`:
```
<!DOCTYPE html>
 <html>
     <head>
         <meta charset="utf-8">
     </head>
     <body>
         <script src="bin/app.bundle.js" charset="utf-8"></script>
     </body>
 </html>
```

When I run webpack and fire up a local server I get the following error in the console:
```
app.bundle.js:178 milsymbol.js 0.6.0 - Copyright (c) 2015 Måns Beckman  http://www.spatialillusions.com
app.bundle.js:49 Uncaught TypeError: MS.symbol is not a constructor
    at Object.<anonymous> (app.bundle.js:49)
    at __webpack_require__ (app.bundle.js:20)
    at app.bundle.js:40
    at app.bundle.js:43
(anonymous) @ app.bundle.js:49
__webpack_require__ @ app.bundle.js:20
(anonymous) @ app.bundle.js:40
(anonymous) @ app.bundle.js:43
```

With the master branch the symbol shows up without errors.

**Comment by spatialillusions** [comment] 2017-01-17 07:42
Thank you very much for your input, I will try this out and see if there is anything I can do to make it work.

**Comment by kjellmf** [comment] 2017-01-17 07:51
I did some research yesterday and found some relevant material. This blog post mentions something about libraryTarget and universal module definition (UMD). 
http://krasimirtsonev.com/blog/article/javascript-library-starter-using-webpack-es6

How webpack resolves packages may also be relevant: https://webpack.github.io/docs/resolving.html

**Comment by spatialillusions** [comment] 2017-01-17 09:00
Thank you very much for your input, I think what I will have to do is to
add:

    libraryTarget: 'umd',
    umdNamedDefine: true

to my webpack.config and things should work then. I will try this evening
and get back to you. Would be really nice to switch to the webpack version
of milsymbol because it will make the code easier to maintain as you stated
from the beginning, I just haven't had time to do it until now. During the
weekend I also got some new API ideas for milsymbol that will make it even
easier to use, and I will hopefully be able to make it backwards compatible
for a few versions.

/Måns

**Comment by kjellmf** [comment] 2017-01-17 10:19
Another thing to consider is to take advantage of the [ES6 module syntax](http://www.2ality.com/2014/09/es6-modules-final.html). This syntax is not supported yet by browsers, but since you have to use a bundler like webpack or rollup anyway, it does not matter. A good example of this is D3 v 4.0 and its modules. The only ES6 feature D3 uses is modules. See for instance the [main fle `index.js`](https://github.com/d3/d3/blob/master/index.js). D3 also have some similarities with `milsymbol` (a global `d3` object, modules that add functionality to the object)

The ES6 module syntax is similar to how modules work in languages like Java, Python and C#. Instead of 
```var MS = require('../src/ms.js');```
you write
```import MS from '../src/ms.js';``` 
You may have to structure your code slightly differently, but personally I find the following code clearer than the original:
```
import MS from '../src/ms.js';
import symbol from '../src/ms.symbol.js';
import {light, medium, dark, framecolor} from '../src/colormodes/';

MS.symbol = symbol;

// Standard colors for symbols
MS.setColorMode('Light', light);
MS.setColorMode('Medium', medium);
MS.setColorMode('Dark', dark);
MS.setColorMode('FrameColor', framecolor);
```
The above code is not the best example but it gives an idea on how ES6 modules work.

**Comment by spatialillusions** [comment] 2017-01-17 10:26
Good import, I was looking at this, but since I was sort of more familiar with require I stuck with that. But I agree with you and will take a look at it. First goal is however to get it working as it is now. Then I might have a look at moving to ES6 modules and then there is the thing to break out all MS methods to separate files and all symbol methods to separate files.

**Comment by spatialillusions** [comment] 2017-01-17 16:14
Did a bunch of fixes and got the code from @kjellmf to work. So now I know that we can get a webpack build of milsymbol that works. Next step is to change to ES6 modules instead and do some more modules of the symbol code.

**Comment by spatialillusions** [comment] 2017-01-17 20:28
Tried to move to ES6, but did run into this:
https://github.com/webpack/webpack/issues/3929
So I think I will wait with moving to ES6 until there is a reliable solution that gives the same output as I have at the moment.

If I don't hear anything about things being broken, I will merge the branch into the master during the upcoming week and open a new issue regarding "Move to ES6".

**Closed** 2017-01-18 16:28 UTC
Labels: help wanted
